# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChukusController do

  # This should return the minimal set of attributes required to create a valid
  # Chuku. As you add validations to Chuku, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChukusController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all chukus as @chukus" do
      chuku = Chuku.create! valid_attributes
      get :index, {}, valid_session
      assigns(:chukus).should eq([chuku])
    end
  end

  describe "GET show" do
    it "assigns the requested chuku as @chuku" do
      chuku = Chuku.create! valid_attributes
      get :show, {:id => chuku.to_param}, valid_session
      assigns(:chuku).should eq(chuku)
    end
  end

  describe "GET new" do
    it "assigns a new chuku as @chuku" do
      get :new, {}, valid_session
      assigns(:chuku).should be_a_new(Chuku)
    end
  end

  describe "GET edit" do
    it "assigns the requested chuku as @chuku" do
      chuku = Chuku.create! valid_attributes
      get :edit, {:id => chuku.to_param}, valid_session
      assigns(:chuku).should eq(chuku)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Chuku" do
        expect {
          post :create, {:chuku => valid_attributes}, valid_session
        }.to change(Chuku, :count).by(1)
      end

      it "assigns a newly created chuku as @chuku" do
        post :create, {:chuku => valid_attributes}, valid_session
        assigns(:chuku).should be_a(Chuku)
        assigns(:chuku).should be_persisted
      end

      it "redirects to the created chuku" do
        post :create, {:chuku => valid_attributes}, valid_session
        response.should redirect_to(Chuku.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chuku as @chuku" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chuku.any_instance.stub(:save).and_return(false)
        post :create, {:chuku => { "user_id" => "invalid value" }}, valid_session
        assigns(:chuku).should be_a_new(Chuku)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chuku.any_instance.stub(:save).and_return(false)
        post :create, {:chuku => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chuku" do
        chuku = Chuku.create! valid_attributes
        # Assuming there are no other chukus in the database, this
        # specifies that the Chuku created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Chuku.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => chuku.to_param, :chuku => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested chuku as @chuku" do
        chuku = Chuku.create! valid_attributes
        put :update, {:id => chuku.to_param, :chuku => valid_attributes}, valid_session
        assigns(:chuku).should eq(chuku)
      end

      it "redirects to the chuku" do
        chuku = Chuku.create! valid_attributes
        put :update, {:id => chuku.to_param, :chuku => valid_attributes}, valid_session
        response.should redirect_to(chuku)
      end
    end

    describe "with invalid params" do
      it "assigns the chuku as @chuku" do
        chuku = Chuku.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chuku.any_instance.stub(:save).and_return(false)
        put :update, {:id => chuku.to_param, :chuku => { "user_id" => "invalid value" }}, valid_session
        assigns(:chuku).should eq(chuku)
      end

      it "re-renders the 'edit' template" do
        chuku = Chuku.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chuku.any_instance.stub(:save).and_return(false)
        put :update, {:id => chuku.to_param, :chuku => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chuku" do
      chuku = Chuku.create! valid_attributes
      expect {
        delete :destroy, {:id => chuku.to_param}, valid_session
      }.to change(Chuku, :count).by(-1)
    end

    it "redirects to the chukus list" do
      chuku = Chuku.create! valid_attributes
      delete :destroy, {:id => chuku.to_param}, valid_session
      response.should redirect_to(chukus_url)
    end
  end

end
