# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReasonsController do

  # This should return the minimal set of attributes required to create a valid
  # Reason. As you add validations to Reason, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "reason" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReasonsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all reasons as @reasons" do
      reason = Reason.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reasons).should eq([reason])
    end
  end

  describe "GET show" do
    it "assigns the requested reason as @reason" do
      reason = Reason.create! valid_attributes
      get :show, {:id => reason.to_param}, valid_session
      assigns(:reason).should eq(reason)
    end
  end

  describe "GET new" do
    it "assigns a new reason as @reason" do
      get :new, {}, valid_session
      assigns(:reason).should be_a_new(Reason)
    end
  end

  describe "GET edit" do
    it "assigns the requested reason as @reason" do
      reason = Reason.create! valid_attributes
      get :edit, {:id => reason.to_param}, valid_session
      assigns(:reason).should eq(reason)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reason" do
        expect {
          post :create, {:reason => valid_attributes}, valid_session
        }.to change(Reason, :count).by(1)
      end

      it "assigns a newly created reason as @reason" do
        post :create, {:reason => valid_attributes}, valid_session
        assigns(:reason).should be_a(Reason)
        assigns(:reason).should be_persisted
      end

      it "redirects to the created reason" do
        post :create, {:reason => valid_attributes}, valid_session
        response.should redirect_to(Reason.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reason as @reason" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reason.any_instance.stub(:save).and_return(false)
        post :create, {:reason => { "reason" => "invalid value" }}, valid_session
        assigns(:reason).should be_a_new(Reason)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reason.any_instance.stub(:save).and_return(false)
        post :create, {:reason => { "reason" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reason" do
        reason = Reason.create! valid_attributes
        # Assuming there are no other reasons in the database, this
        # specifies that the Reason created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reason.any_instance.should_receive(:update_attributes).with({ "reason" => "MyString" })
        put :update, {:id => reason.to_param, :reason => { "reason" => "MyString" }}, valid_session
      end

      it "assigns the requested reason as @reason" do
        reason = Reason.create! valid_attributes
        put :update, {:id => reason.to_param, :reason => valid_attributes}, valid_session
        assigns(:reason).should eq(reason)
      end

      it "redirects to the reason" do
        reason = Reason.create! valid_attributes
        put :update, {:id => reason.to_param, :reason => valid_attributes}, valid_session
        response.should redirect_to(reason)
      end
    end

    describe "with invalid params" do
      it "assigns the reason as @reason" do
        reason = Reason.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reason.any_instance.stub(:save).and_return(false)
        put :update, {:id => reason.to_param, :reason => { "reason" => "invalid value" }}, valid_session
        assigns(:reason).should eq(reason)
      end

      it "re-renders the 'edit' template" do
        reason = Reason.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reason.any_instance.stub(:save).and_return(false)
        put :update, {:id => reason.to_param, :reason => { "reason" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reason" do
      reason = Reason.create! valid_attributes
      expect {
        delete :destroy, {:id => reason.to_param}, valid_session
      }.to change(Reason, :count).by(-1)
    end

    it "redirects to the reasons list" do
      reason = Reason.create! valid_attributes
      delete :destroy, {:id => reason.to_param}, valid_session
      response.should redirect_to(reasons_url)
    end
  end

end
